<DarkTile>:
    canvas.before:
        Color:
            rgb: (0.43, 0.26, 0)
        Rectangle:
            pos: self.pos
            #size: self.width, self.height

<LightTile>:
    canvas.before:
        Color:
            rgb: (0.92, 0.85, 0.72)
        Rectangle:
            pos: self.pos
            #size: self.width, self.height

<DragPiece>:
    # Define the properties for the DragLabel
    drag_rectangle: self.x, self.y, self.width, self.height
    drag_distance: 0